### ISSUE TITLE
Wave with only stroke

### ISSUE THREAD

**Issue by easyfast2008** [narayanacharya6/WaveView#10]
Hi, thanks for you great library, is there any possibility to have a wave with just stroke on it? i mean without the fill color, also I assume the xml waveColor does not support alpha channel for opacity right?

**Comment by easyfast2008** [comment]
Actually i checked your code and modified some codes for myself, I added an styleable key for stroke only or fill and stroke, then in your initPaintPath we can change paint style so it will work easily. I don't know if you will add this option to your code later, but it's a good feature to have. About opacity thing, i just noticed you're changing alphas for multiple waves, so it's not possible to have for multiple waves, but for single waves I changed it for my own needs. Thanks for this great lib, love it...

**Comment by narayanacharya6** [comment]
Great! Would like to see how solved it and if you think it is configurable and something that the library should support out of the box, raise a pull request maybe?
