### ISSUE TITLE
Remove bad tag in XML file

### ISSUE THREAD

**Issue by zunjae** [narayanacharya6/WaveView#12]
android:allowBackup="true"

Please delete this

**Comment by narayanacharya6** [comment]
Hi, it's been a while since I have taken a look at this repo (or Android projects in general). Can you please give the reason or link some documentation as to what has changed that warrants updating this?

**Comment by zunjae** [comment]
It overwrites the value of my project, causing me to add a label saying to ignore your value. I also looked at every other open source library I use and none of them have this value set

**Comment by narayanacharya6** [comment]
Hi after skimming over some info around this over [here](https://stackoverflow.com/a/13806946/5512274) and [here](https://medium.com/@elye.project/2-lines-in-manifest-to-remove-when-sharing-your-android-library-565d4c4af04a), I think it is OK to remove this line.

I will pick this up and hopefully have a new version of the library in the next 24-48 hours.

Thanks for bringing this up.

**Comment by narayanacharya6** [comment]
Hi @zunjae , I have published version 0.9.4 of the library. It should be available in some time. Please let me know how that works out for you.

Thanks!

**Comment by zunjae** [comment]
Works fine, thanks
