### ISSUE TITLE
Play/pause animation

### ISSUE THREAD

**Issue by maxim-petlyuk** [narayanacharya6/WaveView#3]
It would be great to have play/pause functionality for the animation like in the primary source. Your version looks better.

**Comment by narayanacharya6** [comment]
Hey @mpetlyuk . Its been some time I have seen this. Thanks for the suggestion. I'll see what I can do here. Feel free to raise a PR if you can. Thanks :)

**Comment by narayanacharya6** [comment]
Hey @mpetlyuk I have added a few methods to add play/pause functionality. Now available in v0.9.3. Check out the README for the API methods to pause and play a wave and the updated sample under app/. Let me know if that works for you. Thanks!
