### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TyMarc** [narayanacharya6/WaveView#4]
Hi, I was working on an audio recording component for a project I'm working on and I wanted to use your library as a base for my component but I can't see any license in the repo. Were you planning to add one?

**Comment by narayanacharya6** [comment]
Hey @TyMarc Thanks for the PR. I will merge it. And no, I was not planning on adding one. Its been some time I saw this repo. :)

**Comment by TyMarc** [comment]
Hehe, thanks!
