### ISSUE TITLE
Initialise phase variable to a default value.

### ISSUE THREAD

**Issue by narayanacharya6** [narayanacharya6/WaveView#7]
Currently the phase variable is not initialised in the WaveView class. Initialise it to 0 (maybe) to keep in sync with other variables of the class and keep consistent.

**Comment by omgcheese** [comment]
In Java, primitive (`int`, `long`, `double`) type instance variables are set as 0 and reference type (anything other than primitives) are set to `null` by default. If `phase` instance is going to be 0, I don't see a point to set it to zero explicitly

**Comment by narayanacharya6** [comment]
Hmmm, right. Will close this. 

But this actually led me to something I'd like to share. Apparently, initialising redundant values actually takes a 'hit' on performance it seems (based on compiler though). No matter how insignificant but worth knowing.
http://www.javapractices.com/topic/TopicAction.do?Id=14

**Comment by omgcheese** [comment]
Interesting. Thank you for sharing!
