### ISSUE TITLE
Round Corners

### ISSUE THREAD

**Issue by prankhazard** [narayanacharya6/WaveView#9]
Hi and thanks for the awesome library.
I'm unable to create wave view vith rounded corners. How can i achieve that?

**Comment by narayanacharya6** [comment]
Sorry, I did not get your question. Can you give me an example image of what you wish to achieve?

**Comment by prankhazard** [comment]
I want to create a simple card divided in two colors by a custom wave. Basically is a rectangle with border radius and a wave. Here is and example concept. 
https://ibb.co/jbTttU

**Comment by narayanacharya6** [comment]
Hey, I guess the rounded corners can be achieved by dropping the WaveView inside a CardView. 
The rounded edges of the card is what you are looking for I suppose.

**Comment by prankhazard** [comment]
Yes, it's what i'm looking for but unforunately using card view does not work for me

**Comment by narayanacharya6** [comment]
What I am suggesting is that the parent of the WaveView will decide the rounded corners. Also, why does CardView not work for you? Can you share XML snippet of your layout?

**Comment by narayanacharya6** [comment]
Closing issue as no response received. Please reopen if you have something to add here. Thanks!
